[package]
name = "openmobilemaps-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
autocxx = "0.25.0"
autocxx-macro = "0.25.0"
cxx = "1.0"
gl = "0.14.0"
glium = "0.32.1"
glutin = "0.29"
image = "0.24.5"
lazy_static = "1.4.0"
# piston2d-opengl_graphics = "0.82.0"
# sdl2 = "0.35.2"
tokio = {version = "1.26.0", features = ["full"]}
ureq = "2.6.2"
openmobilemaps-sys = { path = "./openmobilemaps-sys"}

[build-dependencies]
autocxx-build = "0.25.0"
miette = { version = "5", features = ["fancy"] }
cc = { version = "1.0.79", features = ["parallel"]}
glob = "0.3.1"
cxx-build = "1.0"